
services:

  musicbox:
    build: .
    volumes:
      - .:/musicbox
    ports:
      - "8000:8000"

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: musicdb


