# Generated by Django 5.2.1 on 2025-05-25 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicbox", "0002_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="playlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="musicbox.playlist",
            ),
        ),
    ]
